### ISSUE TITLE
long speaker bio is truncated

### ISSUE THREAD

**Issue by carlcamera** [xximjasonxx/Codemash#10]
Open app
Swipe to "all sessions"
tap "A"
tap "C"
tap "Cloud Architecture with WIndows Azure (REPEAT SESSION! Wednesday AM Half Day)"
Swipe to speaker

The bio for Mike Wood does not scroll and ends with "You can catch up"

**Comment by xximjasonxx** [comment]
This issue is fixed and will be in the version deployed in late November
