### ISSUE TITLE
Make "Technology" tappable in Details View

### ISSUE THREAD

**Issue by carlcamera** [xximjasonxx/Codemash#11]
1. Open App
2. Tap "search" icon
3. Search for "mongo"
4. Tap 2nd session "Rapid and Scalable.....and Ming"
5. Under "Technology" this session indicates "Python" - make that tappable

Hey Jason, I'm not sure if this is the type of feedback you're looking for.  Technically this is not UI feedback it's functionality feedback. Feel free to close and ignore if you'd rather not get these types of suggestions.

So the scenario or use case that this serves is someone who finds a session that they like and want to find other similar sessions.  In the example above, if I want more about python, I have to back out go to the beginning and dig in again.  It would be handy to be able to tap on the word "python" and then either go to the "by tech" session list for python or perhaps a search results page for "python."

I will only enter this one suggestion today and not create more functionality suggestions until I know whether you're looking for these or not. I appreciate your hard work!

**Comment by xximjasonxx** [comment]
Appreciate this. But I am looking to keep the app pretty simple for this release. But I intend to expand this "group" functionality in the release beyond codemash
