### ISSUE TITLE
Alphabetical Jumplist

### ISSUE THREAD

**Issue by carlcamera** [xximjasonxx/Codemash#6]
When viewing sessions by name and tapping a heading letter, the jump list shows a long list of letters that must be scrolled.

My suggestion for improved UI would be a UI similar to the people hub jump list that
1) shows all letters of the alphabet in a 4x7 grid
2) highlights those letters that match session title first letters

This would remove the need to scroll altogether and mirror the existing familiar jump list paradigm

**Comment by xximjasonxx** [comment]
This is fixed and will be visible in the next deployment
