### ISSUE TITLE
long abstract is truncated

### ISSUE THREAD

**Issue by carlcamera** [xximjasonxx/Codemash#8]
Open app
Swipe to "all sessions"
tap "A"
tap "C"
tap "Cloud Architecture with WIndows Azure (REPEAT SESSION! Wednesday AM Half Day)"
Swipe to abstract

The long abstract is truncated at the bottom.  Not all is visible.  (Or possibly the last line is chopped)

**Comment by xximjasonxx** [comment]
This is fixed and will be visible in the next deployment
